export const GET_URL = "https://app-food1.herokuapp.com/"

export const GET_RECIPES_ALL = 'GET_RECIPES_ALL';
export const GET_RECIPES_FOR_NAME = 'GET_RECIPES_FOR_NAME';
export const GET_RECIPES_DETAIL = 'GET_RECIPES_DETAIL';
export const GET_RECIPES_FOR_DIET = 'GET_RECIPES_FOR_DIET';
export const GET_DIET_TYPES = 'GET_DIET_TYPES';
export const ADD_RECIPE = 'ADD_RECIPE';
export const FILTRED_FOR_NAME_HIGH_TO_LOW = 'FILTRED_FOR_NAME_HIGH_TO_LOW';
export const FILTRED_FOR_NAME_LOW_TO_HIGH = 'FILTRED_FOR_NAME_LOW_TO_HIGH';
export const FILTRED_FOR_SCORE_HIGH_TO_LOW = 'FILTRED_FOR_SCORE_HIGH_TO_LOW';
export const FILTRED_FOR_SCORE_LOW_TO_HIGH = 'FILTRED_FOR_SCORE_LOW_TO_HIGH';
export const FILTRED_FOR_SCORE_HEALTH_HIGH_TO_LOW = 'FILTRED_FOR_SCORE_HEALTH_HIHG_TO_LOW';
export const FILTRED_FOR_SCORE_HEALTH_LOW_TO_HIGH = 'FILTRED_FOR_SCORE_HEALTH_LOW_TO_HIGH';
export const PAGINATE = "PAGINATE";
export const LOADING = "LOADING";
